# Alembic Configuration
# the output encoding used when revision files
# are written from script.py.mako
# string value is passed through the
# call to str.encode()
sqlalchemy.url = postgresql+asyncpg://localhost/placeholder

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

[alembic]
# path to migration scripts
script_location = %(here)s/alembic

# prepend the value of %(here)s to the path
# for Python sys.path, so that it
# contains the directory in which the
# setup.py file resides on installation, as well
# as the current working directory
prepend_sys_path = .

# timezone to use when rendering the
# date within the migration file
# as well as the filename.
# string value is passed to the
# datetime.datetime.utcnow.replace()
# method as the 'tzinfo' argument
# leave as the empty string for localtime
# timezone =

# max length of characters to apply to the
# "slug" field in an alembic revision file
# set to 40 to truncate at 40
# characters
# splice_here = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# version location specification; the value below uses
# the path to the versions/ directory from the config file
# location as the base directory for version files.
# locations = %(here)s/versions

# version path separator; As mentioned in the config init message
# use os.pathsep here if on Windows to use backslash as separator
version_path_separator = os

# the output encoding used when revision files
# are written from script.py.mako
# string value is passed through the
# call to str.encode()
# output_encoding = utf-8
